### ISSUE TITLE
Website will not go live

### ISSUE THREAD

**Issue by ryandods** [ryandods/css-validation-fixes#1]
Website passes all tests on Markbot, naming is correct and everything has been committed but the website won't go live

@hellachella
@raven-rhea

**Comment by raven-rhea** [comment]
Your index file is capitalized. Another student had an issue where they named it incorrectly and then later changed it and it didn't register. If thats the case you have to change the name on the github website directly

**Comment by raven-rhea** [comment]
You can also try making a new index file named correctly copy paste your code into it and delete the other file

**Comment by ryandods** [comment]
Perfect that worked thank you
